---
apiVersion: v1
kind: Service
metadata:
  name: ethereum2-prysm-test
  namespace: test
  labels:
    application: ethereum2-prysm-test
    version: v1
spec:
  type: ClusterIP
  ports:
    - port: 3500
      protocol: TCP
      targetPort: 3500
      name: ext-3500
    - port: 4000
      protocol: TCP
      targetPort: 4000
      name: ext-4000
    - port: 6668
      protocol: TCP
      targetPort: 6668
      name: ext-6668
    - port: 13000
      protocol: TCP
      targetPort: 13000
      name: ext-13000
  selector:
    application: ethereum2-prysm
  sessionAffinity: ClientIP
  sessionAffinityConfig:
    clientIP:
      timeoutSeconds: 10800
---
apiVersion: REPLACE_API_VERSION
kind: StatefulSet
metadata:
  namespace: test
  name: ethereum2-prysm-test
spec:
  replicas: 1
  revisionHistoryLimit: 1
  selector:
    matchLabels:
      name: ethereum2-prysm-test
      application: ethereum2-prysm-test
  serviceName: ethereum2-prysm-test
  template:
    metadata:
      labels:
        name: ethereum2-prysm-test
        application: ethereum2-prysm-test
    spec:
      affinity:
        podAntiAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
          - podAffinityTerm:
              labelSelector:
                matchLabels:
                  application: ethereum2-prysm-test
              topologyKey: kubernetes.io/hostname
            weight: 1
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
            - matchExpressions:
              - key: kubernetes.io/role
                operator: In
                values:
                - blockchain
      containers:
      - name: ethereum2-prysm-test
        image: REPLACE_DOCKER_REPO:REPLACE_IMAGETAG
        imagePullPolicy: Always
        ports:
        - containerPort: 3500
          name: ext-3500
        - containerPort: 4000
          name: ext-4000
        - containerPort: 6668
          name: ext-6668
        - containerPort: 13000
          name: ext-13000
        volumeMounts:
        - mountPath: "/data"
          name: ethereum2-prysm-test
      - name: ubuntu
        image: 121827225315.dkr.ecr.us-west-2.amazonaws.com/infra-stage-repo:ubuntu20
        imagePullPolicy: Always
        args: [bash, -c, sleep infinity]
        volumeMounts:
        - name: ethereum2-script-prysm-test
          mountPath: /root/sync-status.sh
          subPath: sync-status.sh
        readinessProbe:
          exec:
            command:
            - /bin/bash
            - /root/sync-status.sh
          initialDelaySeconds: 10
          periodSeconds: 15
      volumes:
      - persistentVolumeClaim:
          claimName: ethereum2-prysm-test
        name: ethereum2-prysm-test
      - name: ethereum2-script-prysm-test
        configMap:
          name: ethereum2-script-prysm-test
      tolerations:
      - effect: NoSchedule
        key: kubernetes.io/role
        operator: Exists 
  updateStrategy:
    type: RollingUpdate
  volumeClaimTemplates:
  - metadata:
      name: ethereum2-prysm-test
    spec:
      accessModes:
      - ReadWriteOnce
      resources:
        requests:
          storage: 150Gi
      storageClassName: gp2
